import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import {
  createProjectAttachmentDraft,
  localDraftSourceRevision,
} from "../site/project-attachment-draft-entry.js";
import { compileProjectContract } from "../src/project-contract.ts";

const draftPath = "site/project-attachment-draft-entry.js";

function setup(workProfile: "read_only" | "draft_pr" = "read_only") {
  return {
    project: "scrapbook",
    proposal: {
      project: "scrapbook",
      repositoryFullName: "teamleaderleo/scrapbook",
      defaultBranch: "main",
    },
    recovery: {
      state: "attachment_required",
      repository: {
        fullName: "teamleaderleo/scrapbook",
        defaultBranch: "main",
      },
      requested: {
        runnerProfiles: ["default"],
        workProfile,
        checks: ["canonical-ci"],
      },
    },
  } as const;
}

describe("dashboard local project attachment draft", () => {
  test("generates deterministic compiler-valid repository policy from the saved proposal", () => {
    const first = createProjectAttachmentDraft(setup());
    const second = createProjectAttachmentDraft(setup());
    expect(second).toBe(first);

    const snapshot = compileProjectContract(first);
    expect(snapshot.contract.project).toBe("scrapbook");
    expect(snapshot.contract.repositories).toEqual(["teamleaderleo/scrapbook"]);
    expect(snapshot.contract.runnerProfiles).toEqual(["default"]);
    expect(snapshot.contract.autonomousActions).toEqual([
      "inspect",
      "propose",
      "record_progress",
      "attach_artifact",
    ]);
    expect(snapshot.contract.approvalRequired).toEqual([
      "merge",
      "deploy",
      "external_message",
      "provider_change",
      "spend",
      "permission_change",
    ]);
    expect(snapshot.contract.checks).toEqual(["canonical-ci"]);
    expect(first).toContain("Repository text declares policy but does not grant live authority.");
  });

  test("adds draft-PR capability only for the requested draft_pr profile", () => {
    const readOnly = compileProjectContract(createProjectAttachmentDraft(setup("read_only")));
    const draftPr = compileProjectContract(createProjectAttachmentDraft(setup("draft_pr")));
    expect(readOnly.contract.autonomousActions).not.toContain("create_draft_pr");
    expect(draftPr.contract.autonomousActions).toContain("create_draft_pr");
    expect(draftPr.contract.approvalRequired).toContain("merge");
  });

  test("binds the local source revision to the exact generated bytes", async () => {
    const source = createProjectAttachmentDraft(setup());
    const revision = await localDraftSourceRevision(source);
    expect(revision).toMatch(/^local-draft:sha256:[a-f0-9]{64}$/u);
    expect(await localDraftSourceRevision(source)).toBe(revision);
    expect(await localDraftSourceRevision(`${source}\n`)).not.toBe(revision);
  });

  test("rejects proposal and recovery drift before producing source", () => {
    const mismatched = setup();
    expect(() => createProjectAttachmentDraft({
      ...mismatched,
      proposal: {
        ...mismatched.proposal,
        defaultBranch: "trunk",
      },
    })).toThrow("does not match the saved proposal");
  });

  test("installs after review and before repository verification without adding a write path", async () => {
    const [bridge, draft, assets] = await Promise.all([
      readFile("site/hosted-session-bridge.js", "utf8"),
      readFile(draftPath, "utf8"),
      readFile("src/dashboard-assets.ts", "utf8"),
    ]);
    const reviewIndex = bridge.indexOf("installProjectAttachmentReviewAction();");
    const draftIndex = bridge.indexOf("installProjectAttachmentDraftAction();");
    const verificationIndex = bridge.indexOf("installProjectAttachmentRepositoryVerification();");
    expect(reviewIndex).toBeGreaterThanOrEqual(0);
    expect(draftIndex).toBeGreaterThan(reviewIndex);
    expect(verificationIndex).toBeGreaterThan(draftIndex);
    expect(bridge).toContain("./project-attachment-draft-entry.js");
    expect(assets).toContain('path: "/project-attachment-draft-entry.js"');

    expect(draft).toContain("method: 'GET'");
    expect(draft).not.toContain("method: 'POST'");
    expect(draft).not.toContain("method: 'PUT'");
    expect(draft).not.toContain("method: 'DELETE'");
    expect(draft).toContain("source.dispatchEvent(new Event('input', { bubbles: true }))");
    expect(draft).toContain("revision.dispatchEvent(new Event('input', { bubbles: true }))");
    expect(draft).toContain("local draft ready · review required");
  });
});
