export type WorkPulseFixtureState = "queued" | "reserved" | "starting" | "running" | "verifying" | "waiting_external" | "stalled" | "cancelling" | "cancelled" | "blocked" | "succeeded" | "failed";
export type WorkPulseAttentionReason = "human_decision" | "ambiguous_settlement" | "heartbeat_missed" | "lease_expired" | "external_wait_old" | "verification_failed" | "superseded_current" | "blocked" | "stalled" | "failed" | "stale_receipt" | "high_fan_out";
export type WorkPulseRelationKind = "dependency" | "stacked_candidate" | "file_overlap" | "contract_overlap" | "shared_external_gate" | "supersedes" | "handoff";
export interface WorkPulseFixtureAttempt { readonly id: string; readonly outcomeId: string; readonly itemId: string; readonly runId: string; readonly authorityGeneration: number; readonly callsign: string; readonly profile: string; readonly state: WorkPulseFixtureState; readonly phase: string; readonly receiptAgeMinutes: number; readonly receiptLabel: string; readonly candidate: string | null; readonly artifact: string | null; readonly queuePosition: number | "unknown" | null; readonly attentionReasons: readonly WorkPulseAttentionReason[]; readonly blockedFanOut: number; readonly nextAction: string; readonly evidence: string; readonly consequence: "tier_0" | "tier_1" | "tier_2" | "tier_3"; readonly polar: Readonly<{ lane: string; angleDegrees: number; receiptAgeMinutes: number; freshnessRing: "current" | "stale"; blockedFanOut: number }>; }
export interface WorkPulseFixtureRelation { readonly id: string; readonly kind: WorkPulseRelationKind; readonly from: string; readonly to: string; readonly label: string; readonly evidence: string; }
export interface WorkPulseFixtureAttention { readonly id: string; readonly attemptId: string; readonly reason: WorkPulseAttentionReason; readonly label: string; readonly nextAction: string; readonly evidence: string; }
export interface WorkPulseFixtureEvent { readonly id: string; readonly attemptId: string; readonly at: string; readonly kind: "admitted" | "reserved" | "started" | "receipt" | "candidate" | "verification" | "wait" | "stalled" | "decision" | "reconciliation" | "superseded" | "terminal"; readonly label: string; readonly evidence: string; }
export interface WorkPulseFixture { readonly observedAt: string; readonly attempts: readonly WorkPulseFixtureAttempt[]; readonly relations: readonly WorkPulseFixtureRelation[]; readonly attention: readonly WorkPulseFixtureAttention[]; readonly events: readonly WorkPulseFixtureEvent[]; readonly views: readonly Readonly<{ id: "list" | "lanes" | "attention" | "polar" | "timeline"; label: string; purpose: string }>[]; }
export interface WorkPulseFixtureTask { readonly id: string; readonly prompt: string; readonly start: "list" | "lanes" | "attention" | "polar" | "timeline"; readonly success: string; }
export const workPulseFixture: WorkPulseFixture;
export const workPulseFixtureTasks: readonly WorkPulseFixtureTask[];
export function parseWorkPulseFixture(value: unknown): WorkPulseFixture;
export function parseWorkPulseFixtureTasks(value: unknown): readonly WorkPulseFixtureTask[];
